version: '3'
services:
    database:
        image: 'mcr.microsoft.com/mssql/server:2017-latest'
        container_name: 'CARDS_DB'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Passw0rd
        volumes:
            - ./mssql-data:/var/opt/mssql/data
            - ./shared_folder:/mnt/shared_folder
        ports:
            - "1433:1433"