# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: msbuild Cards.sln /verbosity:minimal /p:Configuration=Release /p:Platform=x86

      - name: Copy files
        run: |
          MKDIR BIN
          XCOPY /Y Core\bin\x86\Release\Core.dll BIN
          XCOPY /Y Cards\bin\x86\Release\Cards.exe BIN
          XCOPY /Y Registration\bin\x86\Release\Registration.exe BIN
          XCOPY /Y Settings\bin\x86\Release\Settings.exe BIN
          XCOPY /Y Lib\Newtonsoft.Json.dll BIN
          XCOPY /Y Lib\EPPlus.dll BIN
          XCOPY /Y Lib\Ionic.BZip2.dll BIN
          XCOPY /Y Lib\Ionic.Zip.dll BIN
          XCOPY /Y Lib\Ionic.Zlib.dll BIN

      - uses: actions/upload-artifact@v2
        with:
          name: Cards
          path: BIN
